mode: immediate
branchName: '${issue.number}-${issue.title}'
autoLinkIssue: true
autoCloseIssue: false
createPR: true
branches:
  - label: enhancement
    prefix: feature/
  - label: bug
    prefix: bugfix/