version: '3.5'

services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: web
    ports:
      - '3000:3000'
    restart: always
    volumes:
      - ./web:/app
      # - /app/node_modules
      # - /app/.next
    depends_on:
      - backend

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports: 
      - '3001:3001'
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - database

  database:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'andychow'
      MONGO_INITDB_ROOT_PASSWORD: '1234'