version: '3.5'

services:
  web:
    container_name: web
    build:
      context: ./web
      target: dev
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    restart: always
    command: npm run dev
    volumes:
      - ./web:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend

  backend:
    container_name: backend
    build: 
      context: ./backend
      target: development
      dockerfile: Dockerfile
    ports: 
      - '3001:3001'
    volumes:
      - ./backend://usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev
    # depends_on:
    #   - database

  # database:
  #   container_name: mongodb
  #   image: mongo:6.0
  #   restart: always
  #   ports:
  #     - '27017:27017'
  #   volumes:
  #     - './backend/data:/data/db'
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: 'andychow'
  #     MONGO_INITDB_ROOT_PASSWORD: '1234'