steps:
  # Build the container image
  - id: 'build-container-image'
    name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'gcr.io/expense-tracker-410901/backend:$COMMIT_SHA',
        './backend',
      ]
  # Push the container image to Container Registry
  - id: 'push-image-to-artifact-registry'
    name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/expense-tracker-410901/backend:$COMMIT_SHA']
  # Deploy container image to Cloud Run
  - id: 'deploy-image-to-cloud-run'
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args: [
        '-c',
        'gcloud run deploy expense-tracker-backend --image gcr.io/expense-tracker-410901/backend:$COMMIT_SHA
        --region us-central1
        --update-secrets=MONGODB_CONNECTION_STRING:projects/expense-tracker-backend/secrets/MONGODB_CONNECTION_STRING/versions/1
        ',
      ]
      #  --set-env-vars MONGODB_CONNECTION_STRING=$$SECRET_MONGODB_CONNECTION_STRING
          
    # secretEnv: ['SECRET_MONGODB_CONNECTION_STRING']
images:
  - gcr.io/expense-tracker-410901/backend:$COMMIT_SHA
# availableSecrets:
#   secretManager:
#     - versionName: projects/expense-tracker-410901/secrets/MONGODB_CONNECTION_STRING/versions/1
#       env: 'SECRET_MONGODB_CONNECTION_STRING'
