import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { GoogleOAuthProvider } from "@react-oauth/google";
import { Navbar, SideBar } from "@/components";
import { UserContextProvider } from "../context/UserContext";
import { getCookie } from ".././utils";
import "./globals.css";
import { GuestAlert } from "@/components/GuestAlert";
import { SpeedInsights } from "@vercel/speed-insights/next";
import { Analytics } from "@vercel/analytics/react"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "FinTrack - Your Financial Tracker",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const accessToken = await getCookie("accessToken");

  return (
    <UserContextProvider accessToken={accessToken}>
      <GoogleOAuthProvider clientId={process.env.GOOGLE_CLIENT_ID ?? ""}>
        <html lang="en">
          <body className={[inter.className, "bg-gray-100"].join(" ")}>
            {!Boolean(accessToken) && <GuestAlert />}
            <Navbar />
            <div className="flex bg-gray-100 lg:h-[calc(100vh-112px)]">
              <SideBar />
              <main className="px-4 py-4 flex-1 lg:px-8 lg:py-6 max-w-full">
                {children}
              </main>
            </div>
            <SpeedInsights />
            <Analytics />
          </body>
        </html>
      </GoogleOAuthProvider>
    </UserContextProvider>
  );
}
