on:
  # The issue.opened event below is only needed for the "immediate" mode.
  issues:
    types: [ opened ]

jobs:
  create_issue_branch_job:
    runs-on: ubuntu-latest
    steps:
      - name: Create Issue Branch
        uses: robvanderleek/create-issue-branch@main
        openPR: true
        branches:
          - label: enhancement
            prefix: feature/
          - label: bug
            prefix: bugfix/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}