name: Create Issue Branch

on:
  issues:
    types: [opened]

jobs:
  create_issue_branch_job:
    runs-on: ubuntu-latest
    steps:
      - name: Create Issue Branch
        uses: robvanderleek/create-issue-branch@main
        with:
          branches: |
            - label: enhancement
              prefix: feature/
            - label: bug
              prefix: bugfix/
          openPR: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}